spring:
  datasource:
    url: jdbc:h2:mem:testdb/board
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
