server:
  port: 18082

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
    region: ap-northeast-2

spring:
  autoconfigure:
    exclude: io.awspring.cloud.autoconfigure.s3.S3AutoConfiguration

---

spring:
  profiles:
    active: local
    include: "local-secrets"
