object Versions {
    const val springBootVersion = "4.1.1"
    const val springDependencyManagementVersion = "1.1.7"
    const val springCloudDependenciesVersion = "2025.1.3"
    const val springDocVersion = "3.1.1"
    const val querydslVersion = "5.1.0"
    const val kotlinVersion = "2.4.20"
    const val coroutineVersion = "1.11.0"
    const val sonarqubeVersion = "7.5.0.8588"
    const val ktlintVersion = "14.2.0"
    const val springCloudAwsVersion = "4.2.0"
    const val koverVersion = "0.9.11"
    const val jacksonVersion = "3.2.3"
    const val mysqlVersion = "26.7.0"
    const val p6spyVersion = "2.0.1"
    const val mockkVersion = "1.14.11"
    const val kotlinLoggingVersion = "8.0.4"
}
