name: CI

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ['board-api', 'board-front/board-front-api']

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Prepare Image Name
        id: prep
        run: |
          IMAGE_NAME="${{ matrix.module }}".replace('/', '-').toLowerCase()
          echo "::set-output name=image_name::$IMAGE_NAME"

      - name: Build and Push Image using Jib
        run: ./gradlew :${{ matrix.module }}:jib
        env:
          GHCR_USERNAME: ${{ github.actor }}
          GHCR_PASSWORD: ${{ secrets.GHCR_TOKEN }}
          FROM_IMAGE: ubuntu-24.04
          TO_IMAGE: ghcr.io/dolphago/${{ steps.prep.outputs.image_name }}:latest
