name: CI

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ['board-api', 'board-front:board-front-api']

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build and Push Image using Jib
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          ./gradlew :${{ matrix.module }}:jib -Pjib.to.image=ghcr.io/$REPO_OWNER/${{ matrix.module }}:latest
        env:
          GHCR_USERNAME: ${{ github.actor }}
          GHCR_PASSWORD: ${{ secrets.GHCR_TOKEN }}
          FROM_IMAGE: openjdk:17-jre-slim
